package marketdata

import (
	"context"
	"fmt"
	"time"
)

type RegistryProvider struct {
	now func() time.Time
}

func NewRegistryProvider() *RegistryProvider {
	return &RegistryProvider{now: func() time.Time { return time.Now().UTC() }}
}

func (p *RegistryProvider) Markets(ctx context.Context) ([]Market, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}

	markets := p.fixtureMarkets()
	return markets, nil
}

func (p *RegistryProvider) Quotes(ctx context.Context, assetIDs []string) ([]Quote, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}

	byID := make(map[string]Market)
	for _, market := range p.fixtureMarkets() {
		byID[market.AssetID] = market
	}

	quotes := make([]Quote, 0, len(assetIDs))
	for _, assetID := range assetIDs {
		market, ok := byID[assetID]
		if !ok {
			return nil, fmt.Errorf("unknown asset id %q", assetID)
		}
		quotes = append(quotes, Quote{
			AssetID:    market.AssetID,
			Symbol:     market.Symbol,
			PriceCents: market.PriceCents,
			ChangeBPS:  market.ChangeBPS,
			Source:     market.Source,
			UpdatedAt:  market.UpdatedAt,
		})
	}

	return quotes, nil
}

func (p *RegistryProvider) fixtureMarkets() []Market {
	updatedAt := p.now()
	return []Market{
		{
			AssetID:    "crypto:btc",
			Symbol:     "BTC",
			Name:       "Bitcoin",
			Kind:       AssetKindCrypto,
			Source:     "coingecko",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "crypto:eth",
			Symbol:     "ETH",
			Name:       "Ethereum",
			Kind:       AssetKindCrypto,
			Source:     "coingecko",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "crypto:sol",
			Symbol:     "SOL",
			Name:       "Solana",
			Kind:       AssetKindCrypto,
			Source:     "coingecko",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "crypto:bnb",
			Symbol:     "BNB",
			Name:       "Binance Coin",
			Kind:       AssetKindCrypto,
			Source:     "coingecko",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "crypto:xrp",
			Symbol:     "XRP",
			Name:       "Ripple",
			Kind:       AssetKindCrypto,
			Source:     "coingecko",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "crypto:ada",
			Symbol:     "ADA",
			Name:       "Cardano",
			Kind:       AssetKindCrypto,
			Source:     "coingecko",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "crypto:doge",
			Symbol:     "DOGE",
			Name:       "Dogecoin",
			Kind:       AssetKindCrypto,
			Source:     "coingecko",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "crypto:link",
			Symbol:     "LINK",
			Name:       "Chainlink",
			Kind:       AssetKindCrypto,
			Source:     "coingecko",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "etf:spy",
			Symbol:     "SPY",
			Name:       "S&P 500 ETF",
			Kind:       AssetKindETF,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "etf:qqq",
			Symbol:     "QQQ",
			Name:       "Nasdaq 100 ETF",
			Kind:       AssetKindETF,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "etf:dia",
			Symbol:     "DIA",
			Name:       "Dow Jones ETF",
			Kind:       AssetKindETF,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "etf:iwm",
			Symbol:     "IWM",
			Name:       "Russell 2000 ETF",
			Kind:       AssetKindETF,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "etf:urth",
			Symbol:     "URTH",
			Name:       "MSCI World ETF",
			Kind:       AssetKindETF,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "etf:eem",
			Symbol:     "EEM",
			Name:       "MSCI Emerging Markets ETF",
			Kind:       AssetKindETF,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "etf:acwi",
			Symbol:     "ACWI",
			Name:       "MSCI All Country World ETF",
			Kind:       AssetKindETF,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "etf:vgk",
			Symbol:     "VGK",
			Name:       "FTSE Europe ETF",
			Kind:       AssetKindETF,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "etf:vwo",
			Symbol:     "VWO",
			Name:       "FTSE Emerging Markets ETF",
			Kind:       AssetKindETF,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "etf:xlk",
			Symbol:     "XLK",
			Name:       "Technology Sector SPDR",
			Kind:       AssetKindETF,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "etf:xlf",
			Symbol:     "XLF",
			Name:       "Financial Sector SPDR",
			Kind:       AssetKindETF,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "etf:xlv",
			Symbol:     "XLV",
			Name:       "Health Care Sector SPDR",
			Kind:       AssetKindETF,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "etf:xle",
			Symbol:     "XLE",
			Name:       "Energy Sector SPDR",
			Kind:       AssetKindETF,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "etf:tlt",
			Symbol:     "TLT",
			Name:       "20+ Year Treasury Bond ETF",
			Kind:       AssetKindETF,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "etf:bnd",
			Symbol:     "BND",
			Name:       "Total Bond Market ETF",
			Kind:       AssetKindETF,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "commodity:gld",
			Symbol:     "GLD",
			Name:       "SPDR Gold Shares",
			Kind:       AssetKindCommodity,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "commodity:slv",
			Symbol:     "SLV",
			Name:       "iShares Silver Trust",
			Kind:       AssetKindCommodity,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "commodity:pplt",
			Symbol:     "PPLT",
			Name:       "Aberdeen Physical Platinum",
			Kind:       AssetKindCommodity,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "commodity:pall",
			Symbol:     "PALL",
			Name:       "Aberdeen Physical Palladium",
			Kind:       AssetKindCommodity,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "commodity:uso",
			Symbol:     "USO",
			Name:       "United States Oil Fund",
			Kind:       AssetKindCommodity,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "commodity:ung",
			Symbol:     "UNG",
			Name:       "United States Natural Gas",
			Kind:       AssetKindCommodity,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:aapl",
			Symbol:     "AAPL",
			Name:       "Apple Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:msft",
			Symbol:     "MSFT",
			Name:       "Microsoft Corp.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:googl",
			Symbol:     "GOOGL",
			Name:       "Alphabet Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:amzn",
			Symbol:     "AMZN",
			Name:       "Amazon.com Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:nvda",
			Symbol:     "NVDA",
			Name:       "NVIDIA Corp.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:tsla",
			Symbol:     "TSLA",
			Name:       "Tesla Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:meta",
			Symbol:     "META",
			Name:       "Meta Platforms Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:amd",
			Symbol:     "AMD",
			Name:       "Advanced Micro Devices",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:nflx",
			Symbol:     "NFLX",
			Name:       "Netflix Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:intc",
			Symbol:     "INTC",
			Name:       "Intel Corp.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:avgo",
			Symbol:     "AVGO",
			Name:       "Broadcom Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:csco",
			Symbol:     "CSCO",
			Name:       "Cisco Systems Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:orcl",
			Symbol:     "ORCL",
			Name:       "Oracle Corp.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:adbe",
			Symbol:     "ADBE",
			Name:       "Adobe Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:crm",
			Symbol:     "CRM",
			Name:       "Salesforce Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:qcom",
			Symbol:     "QCOM",
			Name:       "Qualcomm Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:txn",
			Symbol:     "TXN",
			Name:       "Texas Instruments",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:mu",
			Symbol:     "MU",
			Name:       "Micron Technology",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:amat",
			Symbol:     "AMAT",
			Name:       "Applied Materials",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:lrcx",
			Symbol:     "LRCX",
			Name:       "Lam Research Corp.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:now",
			Symbol:     "NOW",
			Name:       "ServiceNow Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:panw",
			Symbol:     "PANW",
			Name:       "Palo Alto Networks",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:ibm",
			Symbol:     "IBM",
			Name:       "IBM Corp.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:intu",
			Symbol:     "INTU",
			Name:       "Intuit Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:sony",
			Symbol:     "SONY",
			Name:       "Sony Group Corp.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:asml",
			Symbol:     "ASML",
			Name:       "ASML Holding",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:tsm",
			Symbol:     "TSM",
			Name:       "Taiwan Semiconductor",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:jpm",
			Symbol:     "JPM",
			Name:       "JPMorgan Chase & Co.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:bac",
			Symbol:     "BAC",
			Name:       "Bank of America",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:wfc",
			Symbol:     "WFC",
			Name:       "Wells Fargo & Co.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:ms",
			Symbol:     "MS",
			Name:       "Morgan Stanley",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:gs",
			Symbol:     "GS",
			Name:       "Goldman Sachs Group",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:c",
			Symbol:     "C",
			Name:       "Citigroup Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:v",
			Symbol:     "V",
			Name:       "Visa Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:ma",
			Symbol:     "MA",
			Name:       "Mastercard Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:axp",
			Symbol:     "AXP",
			Name:       "American Express",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:pypl",
			Symbol:     "PYPL",
			Name:       "PayPal Holdings",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:cof",
			Symbol:     "COF",
			Name:       "Capital One Financial",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:blk",
			Symbol:     "BLK",
			Name:       "BlackRock Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:schw",
			Symbol:     "SCHW",
			Name:       "Charles Schwab Corp.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:brk.b",
			Symbol:     "BRK.B",
			Name:       "Berkshire Hathaway",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:jnj",
			Symbol:     "JNJ",
			Name:       "Johnson & Johnson",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:lly",
			Symbol:     "LLY",
			Name:       "Eli Lilly & Co.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:unh",
			Symbol:     "UNH",
			Name:       "UnitedHealth Group",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:pfe",
			Symbol:     "PFE",
			Name:       "Pfizer Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:mrk",
			Symbol:     "MRK",
			Name:       "Merck & Co. Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:abbv",
			Symbol:     "ABBV",
			Name:       "AbbVie Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:tmo",
			Symbol:     "TMO",
			Name:       "Thermo Fisher Scientific",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:abt",
			Symbol:     "ABT",
			Name:       "Abbott Laboratories",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:dhr",
			Symbol:     "DHR",
			Name:       "Danaher Corp.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:bmy",
			Symbol:     "BMY",
			Name:       "Bristol-Myers Squibb",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:amgn",
			Symbol:     "AMGN",
			Name:       "Amgen Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:gild",
			Symbol:     "GILD",
			Name:       "Gilead Sciences",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:wmt",
			Symbol:     "WMT",
			Name:       "Walmart Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:hd",
			Symbol:     "HD",
			Name:       "Home Depot Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:mcd",
			Symbol:     "MCD",
			Name:       "McDonald's Corp.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:nke",
			Symbol:     "NKE",
			Name:       "Nike Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:sbux",
			Symbol:     "SBUX",
			Name:       "Starbucks Corp.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:tgt",
			Symbol:     "TGT",
			Name:       "Target Corp.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:low",
			Symbol:     "LOW",
			Name:       "Lowe's Companies",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:tjx",
			Symbol:     "TJX",
			Name:       "TJX Companies Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:bkng",
			Symbol:     "BKNG",
			Name:       "Booking Holdings",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:pg",
			Symbol:     "PG",
			Name:       "Procter & Gamble",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:ko",
			Symbol:     "KO",
			Name:       "Coca-Cola Co.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:pep",
			Symbol:     "PEP",
			Name:       "PepsiCo Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:cost",
			Symbol:     "COST",
			Name:       "Costco Wholesale",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:pm",
			Symbol:     "PM",
			Name:       "Philip Morris Int.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:mo",
			Symbol:     "MO",
			Name:       "Altria Group Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:el",
			Symbol:     "EL",
			Name:       "Estee Lauder Cos.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:cl",
			Symbol:     "CL",
			Name:       "Colgate-Palmolive",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:ge",
			Symbol:     "GE",
			Name:       "General Electric",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:cat",
			Symbol:     "CAT",
			Name:       "Caterpillar Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:hon",
			Symbol:     "HON",
			Name:       "Honeywell Int.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:ups",
			Symbol:     "UPS",
			Name:       "United Parcel Service",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:fdx",
			Symbol:     "FDX",
			Name:       "FedEx Corp.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:de",
			Symbol:     "DE",
			Name:       "Deere & Co.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:ba",
			Symbol:     "BA",
			Name:       "Boeing Co.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:lmt",
			Symbol:     "LMT",
			Name:       "Lockheed Martin",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:rtx",
			Symbol:     "RTX",
			Name:       "RTX Corp.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:xom",
			Symbol:     "XOM",
			Name:       "Exxon Mobil Corp.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:cvx",
			Symbol:     "CVX",
			Name:       "Chevron Corp.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:cop",
			Symbol:     "COP",
			Name:       "ConocoPhillips",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:slb",
			Symbol:     "SLB",
			Name:       "Schlumberger Ltd.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:dis",
			Symbol:     "DIS",
			Name:       "Walt Disney Co.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:cmcsa",
			Symbol:     "CMCSA",
			Name:       "Comcast Corp.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:t",
			Symbol:     "T",
			Name:       "AT&T Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:vz",
			Symbol:     "VZ",
			Name:       "Verizon Commun.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:spot",
			Symbol:     "SPOT",
			Name:       "Spotify Technology",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:f",
			Symbol:     "F",
			Name:       "Ford Motor Co.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:gm",
			Symbol:     "GM",
			Name:       "General Motors",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:tm",
			Symbol:     "TM",
			Name:       "Toyota Motor Corp.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:uber",
			Symbol:     "UBER",
			Name:       "Uber Technologies",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:abnb",
			Symbol:     "ABNB",
			Name:       "Airbnb Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:sq",
			Symbol:     "SQ",
			Name:       "Block Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:coin",
			Symbol:     "COIN",
			Name:       "Coinbase Global",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:pltr",
			Symbol:     "PLTR",
			Name:       "Palantir Technologies",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:snow",
			Symbol:     "SNOW",
			Name:       "Snowflake Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:crwd",
			Symbol:     "CRWD",
			Name:       "CrowdStrike Holdings",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:shop",
			Symbol:     "SHOP",
			Name:       "Shopify Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
		{
			AssetID:    "stock:nvax",
			Symbol:     "NVAX",
			Name:       "Novavax Inc.",
			Kind:       AssetKindStock,
			Source:     "finnhub",
			PriceCents: 0,
			ChangeBPS:  0,
			UpdatedAt:  updatedAt,
		},
	}
}
